//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhedit.MHEditServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientResponseOfbase64Binary", Namespace="http://schemas.datacontract.org/2004/07/MHEdit.Web.Models")]
    [System.SerializableAttribute()]
    public partial class ClientResponseOfbase64Binary : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessfulField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PayloadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccessful {
            get {
                return this.IsSuccessfulField;
            }
            set {
                if ((this.IsSuccessfulField.Equals(value) != true)) {
                    this.IsSuccessfulField = value;
                    this.RaisePropertyChanged("IsSuccessful");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Payload {
            get {
                return this.PayloadField;
            }
            set {
                if ((object.ReferenceEquals(this.PayloadField, value) != true)) {
                    this.PayloadField = value;
                    this.RaisePropertyChanged("Payload");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientResponseOfboolean", Namespace="http://schemas.datacontract.org/2004/07/MHEdit.Web.Models")]
    [System.SerializableAttribute()]
    public partial class ClientResponseOfboolean : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessfulField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PayloadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccessful {
            get {
                return this.IsSuccessfulField;
            }
            set {
                if ((this.IsSuccessfulField.Equals(value) != true)) {
                    this.IsSuccessfulField = value;
                    this.RaisePropertyChanged("IsSuccessful");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Payload {
            get {
                return this.PayloadField;
            }
            set {
                if ((this.PayloadField.Equals(value) != true)) {
                    this.PayloadField = value;
                    this.RaisePropertyChanged("Payload");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientResponseOfstring", Namespace="http://schemas.datacontract.org/2004/07/MHEdit.Web.Models")]
    [System.SerializableAttribute()]
    public partial class ClientResponseOfstring : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessfulField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayloadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccessful {
            get {
                return this.IsSuccessfulField;
            }
            set {
                if ((this.IsSuccessfulField.Equals(value) != true)) {
                    this.IsSuccessfulField = value;
                    this.RaisePropertyChanged("IsSuccessful");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Payload {
            get {
                return this.PayloadField;
            }
            set {
                if ((object.ReferenceEquals(this.PayloadField, value) != true)) {
                    this.PayloadField = value;
                    this.RaisePropertyChanged("Payload");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MHEditServiceReference.IMHEdit")]
    public interface IMHEdit {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMHEdit/GetEncryptionKey", ReplyAction="http://tempuri.org/IMHEdit/GetEncryptionKeyResponse")]
        mhedit.MHEditServiceReference.ClientResponseOfbase64Binary GetEncryptionKey();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMHEdit/GetEncryptionKey", ReplyAction="http://tempuri.org/IMHEdit/GetEncryptionKeyResponse")]
        System.Threading.Tasks.Task<mhedit.MHEditServiceReference.ClientResponseOfbase64Binary> GetEncryptionKeyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMHEdit/Login", ReplyAction="http://tempuri.org/IMHEdit/LoginResponse")]
        mhedit.MHEditServiceReference.ClientResponseOfboolean Login(string encryptedUsername, string encryptedPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMHEdit/Login", ReplyAction="http://tempuri.org/IMHEdit/LoginResponse")]
        System.Threading.Tasks.Task<mhedit.MHEditServiceReference.ClientResponseOfboolean> LoginAsync(string encryptedUsername, string encryptedPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMHEdit/SubmitMaze", ReplyAction="http://tempuri.org/IMHEdit/SubmitMazeResponse")]
        mhedit.MHEditServiceReference.ClientResponseOfboolean SubmitMaze(string encryptedUsername, string encryptedPassword, byte[] maze, byte[] image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMHEdit/SubmitMaze", ReplyAction="http://tempuri.org/IMHEdit/SubmitMazeResponse")]
        System.Threading.Tasks.Task<mhedit.MHEditServiceReference.ClientResponseOfboolean> SubmitMazeAsync(string encryptedUsername, string encryptedPassword, byte[] maze, byte[] image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMHEdit/LogException", ReplyAction="http://tempuri.org/IMHEdit/LogExceptionResponse")]
        mhedit.MHEditServiceReference.ClientResponseOfstring LogException(string message, string source, string stackTrace, string username, string version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMHEdit/LogException", ReplyAction="http://tempuri.org/IMHEdit/LogExceptionResponse")]
        System.Threading.Tasks.Task<mhedit.MHEditServiceReference.ClientResponseOfstring> LogExceptionAsync(string message, string source, string stackTrace, string username, string version);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMHEditChannel : mhedit.MHEditServiceReference.IMHEdit, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MHEditClient : System.ServiceModel.ClientBase<mhedit.MHEditServiceReference.IMHEdit>, mhedit.MHEditServiceReference.IMHEdit {
        
        public MHEditClient() {
        }
        
        public MHEditClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MHEditClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MHEditClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MHEditClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public mhedit.MHEditServiceReference.ClientResponseOfbase64Binary GetEncryptionKey() {
            return base.Channel.GetEncryptionKey();
        }
        
        public System.Threading.Tasks.Task<mhedit.MHEditServiceReference.ClientResponseOfbase64Binary> GetEncryptionKeyAsync() {
            return base.Channel.GetEncryptionKeyAsync();
        }
        
        public mhedit.MHEditServiceReference.ClientResponseOfboolean Login(string encryptedUsername, string encryptedPassword) {
            return base.Channel.Login(encryptedUsername, encryptedPassword);
        }
        
        public System.Threading.Tasks.Task<mhedit.MHEditServiceReference.ClientResponseOfboolean> LoginAsync(string encryptedUsername, string encryptedPassword) {
            return base.Channel.LoginAsync(encryptedUsername, encryptedPassword);
        }
        
        public mhedit.MHEditServiceReference.ClientResponseOfboolean SubmitMaze(string encryptedUsername, string encryptedPassword, byte[] maze, byte[] image) {
            return base.Channel.SubmitMaze(encryptedUsername, encryptedPassword, maze, image);
        }
        
        public System.Threading.Tasks.Task<mhedit.MHEditServiceReference.ClientResponseOfboolean> SubmitMazeAsync(string encryptedUsername, string encryptedPassword, byte[] maze, byte[] image) {
            return base.Channel.SubmitMazeAsync(encryptedUsername, encryptedPassword, maze, image);
        }
        
        public mhedit.MHEditServiceReference.ClientResponseOfstring LogException(string message, string source, string stackTrace, string username, string version) {
            return base.Channel.LogException(message, source, stackTrace, username, version);
        }
        
        public System.Threading.Tasks.Task<mhedit.MHEditServiceReference.ClientResponseOfstring> LogExceptionAsync(string message, string source, string stackTrace, string username, string version) {
            return base.Channel.LogExceptionAsync(message, source, stackTrace, username, version);
        }
    }
}
