<?xml version="1.0" encoding="utf-8"?>
<ArrayOfIonCannonBehavior xmlns:MHEdit="http://mhedit.askey.org">
  <IonCannonBehavior p3:type="Pause" xmlns:p3="http://www.w3.org/2001/XMLSchema-instance">
    <WaitFrames>64</WaitFrames>
  </IonCannonBehavior>
  <IonCannonBehavior p3:type="OrientAndFire" xmlns:p3="http://www.w3.org/2001/XMLSchema-instance">
    <Orientation>DownRight</Orientation>
    <RotateSpeed>Fast</RotateSpeed>
    <ShotSpeed>16</ShotSpeed>
  </IonCannonBehavior>
  <IonCannonBehavior p3:type="OrientAndFire" xmlns:p3="http://www.w3.org/2001/XMLSchema-instance">
    <Orientation>DownRight</Orientation>
    <RotateSpeed>Fast</RotateSpeed>
    <ShotSpeed>16</ShotSpeed>
  </IonCannonBehavior>
  <IonCannonBehavior p3:type="Pause" xmlns:p3="http://www.w3.org/2001/XMLSchema-instance">
    <WaitFrames>16</WaitFrames>
  </IonCannonBehavior>
  <IonCannonBehavior p3:type="ReturnToStart" xmlns:p3="http://www.w3.org/2001/XMLSchema-instance" />
</ArrayOfIonCannonBehavior>